### ISSUE TITLE
Create tour info API

### ISSUE THREAD

**Issue by hienlh** [Ginkgo-App/ginkgo-scrum#13]

**Comment by hienlh** [comment]
Lỗi khi thử trên app
![DeepinScreenshot_select-area_20200611235142.png](https://images.zenhubusercontent.com/5c79f12fcfa1d10365962aa0/c8633d96-b980-4514-880b-6d744a2dd0b8)

Tương tự khi thử bằng swagger
![DeepinScreenshot_select-area_20200611235329.png](https://images.zenhubusercontent.com/5c79f12fcfa1d10365962aa0/eb822328-489c-4f8e-ab16-19c68fd30a8a)

**Comment by ThanhDuyPhan** [comment]
Đã sửa xong

=> Nguyên nhân: do sai tên properties

**Comment by hienlh** [comment]
Lỗi khác rồi 
![DeepinScreenshot_select-area_20200613095751.png](https://images.zenhubusercontent.com/5c79f12fcfa1d10365962aa0/4e0fd85a-c522-4116-855f-22b13e6fa618)

**Comment by ThanhDuyPhan** [comment]
Lỗi do đang migrate database price từ int -> float

**Comment by hienlh** [comment]
Lỗi tiếp
![DeepinScreenshot_select-area_20200613100211.png](https://images.zenhubusercontent.com/5c79f12fcfa1d10365962aa0/d19db5ce-d197-43f0-8f73-47a3a782de75)

**Comment by ThanhDuyPhan** [comment]
Đã fix
